name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# name: Build and Release Executable

#on:
 # schedule:
  #  - cron: "0 3 * * *" # Executa diariamente às 02:00 UTC
  #workflow_dispatch: # Permite execução manual, se necessário

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: python build_executable.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: signit-executable
        path: dist/signit
        if-no-files-found: error

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-build-${{ github.run_id }}
        release_name: Nightly Build ${{ github.run_id }}
        draft: false
        prerelease: true

    - name: Upload Executable to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/signit
        asset_name: signit
        asset_content_type: application/octet-stream
